name: am_PlayerSize
author: emanuele0204
api: [3.0.0-ALPHA7, 3.0.1]
main: emanuele0204\PlayerSize\PlayerSize
version: 1.0

permissions:
 playersize:
  children:
   playersize.command:
    children:
     playersize.command.size:
      default: op
